import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "~/components/ui/sonner";
import { ConvexClientProvider } from "./_components/convex-client-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      className={`${geist.variable} dark`}
      lang="en"
      suppressHydrationWarning
    >
      <body>
        <ConvexClientProvider>{children}</ConvexClientProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
