name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

jobs:
  lint:
    name: Biome Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i
        
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.5
      
      - name: Run Biome
        run: bun biome ci 
